log_level: 0
server:
  http:
    enable: true
    web: true
    swagger: true
    host: 0.0.0.0
    port: 8080
  grpc:
    enable: true
    host: 0.0.0.0
    port: 8081
    reflect: true
  health: true
  cors_debug: false
  origins:
    - "*"
  max_message_size: 512000000
database:
  enable: true
  host: 0.0.0.0
  port: 5432
  name: cdx_db
  user: cdx_user
  pass: 112233445566
cyclonedx:
  min_transitive_severity: 1.0
  max_ui_depth_level: 10